---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

**12.1 Prerequisites**
- I encountered no problems in this step. I had all of the prerequisites covered and encountered no trouble in the following steps. 
- I did no have Git on my laptop so I used Xcode Command Lines to download it then I was ready to go.

**12.2 Make a repo on GitHub**
- This was rather easy. Because the repo was already created, most of this step was already completed. This made for an error free step. 
- I agree, the repo was all set. 

**12.3 Clone the test GitHub repository to your computer via RStudio**
- This step is where I ran into my first issue. After RStudio prompted me to enter my username and password for github, it would say that I did not have the proper authorization. I discovered that it required an access key in place of my password. After a google search, I learned how to create an access code, did so, and entered it into RStudio. This gave me proper access to create a new project in RStudio through Git. I then found the README.md file and was able to open it in my new project. 
- I encountered no issues with this step.
**12.4 Make local changes, save commit**
- After opening the README.md file, I was successfully able to modify the document and add the correct line from the instructions. After this, I opened the "Git" tab in the top right pane and checked the "staged" box next to the file. I was then successfully able to locate the "commit" tab and added the correct message from the instructions. Overall, I did not run into any issues during this step. 
- I followed the same instructions, and I was able to commit my changes with no issues.

**12.5 Push Your local changes online to GitHub**
- During this step I was successfully able to push and pull the changes in my local file and send them to GitHUb. I did not experience any credential challenge, and I did not face any other errors or troubles in this step. 
- This is where I ran into an authentication issue. I needed to set up a personal access token in github so then I could push my new line in the repo.

**12.6 Confirm the local change propagated to the GitHub remote**
- During this final step, I went back to my GitHub browser in order to verify that the local changes were sent to GitHub. I was able to see the new line in the README.md file and the new commit that was created. Overall, I was able to verify that these changes were made successfully 
- In this step, I also checked the repo thoroughly to see that my changes went through, and there was a new additional line in the README.md file. 


